controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_catch_all:
    path: /{any}
    controller: App\Controller\ErrorController::show404
    requirements:
        any: ".*"